// <auto-generated />
using LMSProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LMSProject.Data.Migrations
{
    [DbContext(typeof(LMSProjectDbContext))]
    [Migration("20201219210305_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("LMSProject.Core.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sections");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Section");
                });

            modelBuilder.Entity("LMSProject.Core.Course", b =>
                {
                    b.HasBaseType("LMSProject.Core.Section");

                    b.HasDiscriminator().HasValue("Course");
                });

            modelBuilder.Entity("LMSProject.Core.Lesson", b =>
                {
                    b.HasBaseType("LMSProject.Core.Section");

                    b.HasDiscriminator().HasValue("Lesson");
                });

            modelBuilder.Entity("LMSProject.Core.Module", b =>
                {
                    b.HasBaseType("LMSProject.Core.Section");

                    b.HasDiscriminator().HasValue("Module");
                });
#pragma warning restore 612, 618
        }
    }
}
